config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  resources :expenses
  resources :chore_entries
  resources :chores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/chore_entry.rb
class ChoreEntry < ApplicationRecord
  belongs_to :chore

  validates :date, presence: true

  before_create :set_value

  def name
    chore.name
  end

  def start_time
    date
  end

  def set_value
    self.value = chore.value
  end
end

app/models/chore_entry_view_model.rb
class ChoreEntryViewModel
  include ActiveModel::API
  include ActiveModel::Model

  attr_writer :chore_entries
  attr_reader :chores
  attr_accessor :date

  validates :date, presence: true

  def chore_entries
    @chore_entries ||= build_chore_entries
  end

  def build_chore_entries
    Array(chores).map { ChoreEntry.find_or_initialize_by(chore: _1, date:) }
  end

  def chore_entries_attributes=(attr)
    @chore_entries = attr.map do |(id, entry_params)|
      ChoreEntry.find_or_initialize_by(chore_id: entry_params[:chore_id], date: entry_params[:date]).tap { _1.completed = entry_params[:completed]}
    end
  end

  def chores=(value)
    @chores = value
  end

  def save
    ChoreEntry.transaction do
      chore_entries.all?(&:save!)
    end
  rescue => ex
    errors.add(:chore_entries, "Unable to save all entries")
    false
  end
end

app/controllers/chore_entries_controller.rb
class ChoreEntriesController < ApplicationController
  before_action :set_chore_entry_view_model, only: %i[ new  ]

  # GET /chore_entries or /chore_entries.json
  def index
    @chore_entries = ChoreEntry.where(completed: true, date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  # GET /chore_entries/1 or /chore_entries/1.json
  def show
    @chore_entry = ChoreEntry.find(params[:id])
  end

  # GET /chore_entries/new
  def new
  end

  # GET /chore_entries/1/edit
  def edit
    @chore_entry_view_model = ChoreEntryViewModel.new(chore_entries:, chores:)
  end

  # POST /chore_entries or /chore_entries.json
  def create
    @chore_entry_view_model = ChoreEntryViewModel.new(chore_entry_view_model_params.merge(chores:))

    respond_to do |format|
      if @chore_entry_view_model.save
        format.html { redirect_to chore_entries_url, notice: "Chore entries were successfully created." }
        format.json { render json: @chore_entry_view_model.chore_entries, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chore_entry_view_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chore_entries/1 or /chore_entries/1.json
  def update
    @chore_entry_view_model = ChoreEntryViewModel.new(({chore_entries:, chores:}).merge(chore_entry_view_model_params))

    respond_to do |format|
      if @chore_entry_view_model.save
        format.html { redirect_to chore_entries_url, notice: "Chore entries were successfully created." }
        format.json { render json: @chore_entry_view_model.chore_entries, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chore_entry_view_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chore_entries/1 or /chore_entries/1.json
  def destroy
    @chore_entry = ChoreEntry.find(params[:id])
    @chore_entry.destroy!

    respond_to do |format|
      format.html { redirect_to chore_entries_url, notice: "Chore entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def chores
      @chores ||= Chore.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_chore_entry_view_model
      @chore_entry_view_model = ChoreEntryViewModel.new(chores:, date: start_date)
    end

    # Only allow a list of trusted parameters through.
    def chore_entry_view_model_params
      params.require(:chore_entry_view_model).permit(:date, chore_entries_attributes: [:chore_id, :completed, :date ])
    end

    def chore_entries
      @chore_entries ||= begin 
        ChoreEntry.where(date: start_date)
      end
    end

    def start_date
      @start_date ||= params.fetch(:start_date, Date.today).to_date
    end
end

app/helpers/chore_entries_helper.rb
module ChoreEntriesHelper
  def day_color(date, chores)
    return if date >= Date.today
    if chores.any?
      "done"
    else
      "pending"
    end
  end
end

app/views/chore_entries/_chore_entry.html.erb
<div id="<%= dom_id chore_entry %>">
  <p>
    <strong>Chore:</strong>
    <%= chore_entry.chore_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= chore_entry.date %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= chore_entry.completed %>
  </p>

</div>

app/views/chore_entries/_form.html.erb
<%= simple_form_for(chore_entry_view_model, url: chore_entries_url) do |form| %>
  <% if chore_entry_view_model.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chore_entry_view_model.errors.count, "error") %> prohibited this chore_entry from being saved:</h2>

      <ul>
        <% chore_entry_view_model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <h3> <%= chore_entry_view_model.date %> </h3>

  <%= form.input :date, as: :hidden  %>

  <hr>

  <%= form.simple_fields_for :chore_entries do |entry| %>
    <% if entry.object.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(entry.object.errors.count, "error") %> prohibited <%= entry.object.name %> from being saved:</h2>

        <ul>
          <% entry.object.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <%= entry.input :chore_id, as: :hidden %>
    <%= entry.input :date, as: :hidden %>
    <%= entry.input :completed, as: :boolean, label: entry.object.name %>
  <% end %>

  <div>
    <%= form.button :submit %>
  </div>
<% end %>

app/views/chore_entries/edit.html.erb
<h1>Editing chore entry</h1>

<%= render "form", chore_entry_view_model: @chore_entry_view_model %>

<br>

<div>
  <%= link_to "Back to chore entries", chore_entries_path %>
</div>

app/views/chore_entries/index.html.erb
<% content_for :heading, "Chore entries" %>

<p style="color: green"><%= notice %></p>

<%= month_calendar(events: @chore_entries) do |date, chores| %>
  <div class="<%= day_color(date, chores) %>">
    <%= date %>
  </div>

  <% if chores.any? %>
    <ul>
      <% chores.each do |chore| %>
        <li>
          <%= chore.name %>
        </li>
      <% end %>
    </ul>
    <%= link_to "Edit", edit_chore_entry_path(date, start_date: date), class: "btn btn-secondary" %>
  <% elsif date <= Date.today %>
    <%= link_to "Add chores", new_chore_entry_path(start_date: date), class: "btn btn-primary" %>
  <% end %>
<% end %>

<style>
.done { background-color: #90EE90; }
.pending { background-color: #FF7F7F; }
</style>

app/views/chore_entries/new.html.erb
<h1>New chore entry</h1>


<%= render "form", chore_entry_view_model: @chore_entry_view_model %>

<br>

<div>
  <%= link_to "Back to chore entries", chore_entries_path %>
</div>

app/views/chore_entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chore_entry %>

<div>
  <%= link_to "Edit this chore entry", edit_chore_entry_path(@chore_entry) %> |
  <%= link_to "Back to chore entries", chore_entries_path %>

  <%= button_to "Destroy this chore entry", @chore_entry, method: :delete %>
</div>