config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  resources :expenses
  resources :chore_entries
  resources :chores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/chore.rb
class Chore < ApplicationRecord
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: %i[ show edit update destroy ]

  # GET /chores or /chores.json
  def index
    @chores = Chore.page(params[:page]).per(20)
  end

  # GET /chores/1 or /chores/1.json
  def show
  end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores or /chores.json
  def create
    @chore = Chore.new(chore_params)

    respond_to do |format|
      if @chore.save
        format.html { redirect_to chore_url(@chore), notice: "Chore was successfully created." }
        format.json { render :show, status: :created, location: @chore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1 or /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to chore_url(@chore), notice: "Chore was successfully updated." }
        format.json { render :show, status: :ok, location: @chore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1 or /chores/1.json
  def destroy
    @chore.destroy!

    respond_to do |format|
      format.html { redirect_to chores_url, notice: "Chore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chore_params
      params.require(:chore).permit(:name, :description, :value)
    end
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_chore.html.erb
<div id="<%= dom_id chore %>">
  <p>
    <strong>Name:</strong>
    <%= chore.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= chore.description %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= chore.value %>
  </p>

</div>

app/views/chores/_form.html.erb
<%= form_with(model: chore) do |form| %>
  <% if chore.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
        <% chore.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render "form", chore: @chore %>

<br>

<div>
  <%= link_to "Show this chore", @chore %> |
  <%= link_to "Back to chores", chores_path %>
</div>

app/views/chores/index.html.erb
<% content_for :heading, "Chores" %>

<p style="color: green"><%= notice %></p>

<%= link_to "New chore", new_chore_path, class: "btn btn-primary" %>

<div id="chores">
  <%= paginate @chores %>
  <% @chores.each do |chore| %>
    <%= render chore %>
    <p>
      <%= link_to "Show this chore", chore %>
    </p>
  <% end %>
  <%= paginate @chores %>
</div>

<%= link_to "New chore", new_chore_path, class: "btn btn-primary" %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render "form", chore: @chore %>

<br>

<div>
  <%= link_to "Back to chores", chores_path %>
</div>

app/views/chores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chore %>

<div>
  <%= link_to "Edit this chore", edit_chore_path(@chore) %> |
  <%= link_to "Back to chores", chores_path %>

  <%= button_to "Destroy this chore", @chore, method: :delete %>
</div>