config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  resources :expenses
  resources :chore_entries
  resources :chores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/views/layouts/_navigation.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <%= link_to root_path, class: "nav-link" do %>
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        <% end %>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Tracking
    </div>

    <li class="nav-item active">
        <%= link_to chore_entries_path, class: "nav-link" do %>
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Chore Entries</span>
        <% end %>
    </li>
    <li class="nav-item active">
    <%= link_to expenses_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Expenses</span>
    <% end %>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Management
    </div>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <%= link_to chores_path, class: "nav-link" do %>
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Chores</span>
        <% end %>
    </li>

</ul>
<!-- End of Sidebar -->

app/views/layouts/_page_heading.html.erb
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"><%= yield(:heading) %></h1>
</div>

app/views/layouts/_topbar.html.erb
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
</nav>
<!-- End of Topbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChoreTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <%= render partial: 'layouts/navigation' %>
      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">

          <!-- Main Content -->
          <div id="content">
            <%= render partial: 'layouts/topbar' %>
            <!-- Begin Page Content -->
            <div class="container-fluid">
              <%= render partial: 'layouts/page_heading' %>
              <%= yield %>
            </div>
          </div>
      </div>
    </div>
  </body>
</html>